import type { performanceRating } from "./column";

export const performanceData: performanceRating[] = [
  {
    id: 1,
    title: "مدیریت پروژه",
    position: "مدیر پروژه",
    totalRating: 5,
    addedBy: "علی رضایی",
    createdAt: new Date("2025-01-05"),
  },
  {
    id: 2,
    title: "تحلیل بازار",
    position: "تحلیلگر بازار",
    totalRating: 4,
    addedBy: "سارا احمدی",
    createdAt: new Date("2025-02-10"),
  },
  {
    id: 3,
    title: "طراحی رابط کاربری",
    position: "طراح UI/UX",
    totalRating: 3,
    addedBy: "مهدی کریمی",
    createdAt: new Date("2025-03-02"),
  },
  {
    id: 4,
    title: "توسعه نرم‌افزار",
    position: "برنامه‌نویس",
    totalRating: 4,
    addedBy: "نگار محمدی",
    createdAt: new Date("2025-04-15"),
  },
  {
    id: 5,
    title: "مدیریت مالی",
    position: "حسابدار",
    totalRating: 5,
    addedBy: "رضا حسینی",
    createdAt: new Date("2025-05-01"),
  },
  {
    id: 6,
    title: "پشتیبانی فنی",
    position: "کارشناس پشتیبانی",
    totalRating: 2,
    addedBy: "الهام نادری",
    createdAt: new Date("2025-05-22"),
  },
  {
    id: 7,
    title: "مدیریت منابع انسانی",
    position: "کارشناس HR",
    totalRating: 4,
    addedBy: "امین مرادی",
    createdAt: new Date("2025-06-12"),
  },
  {
    id: 8,
    title: "تولید محتوا",
    position: "کارشناس محتوا",
    totalRating: 3,
    addedBy: "سمانه موسوی",
    createdAt: new Date("2025-06-28"),
  },
  {
    id: 9,
    title: "بازاریابی دیجیتال",
    position: "کارشناس مارکتینگ",
    totalRating: 5,
    addedBy: "کامران طاهری",
    createdAt: new Date("2025-07-08"),
  },
  {
    id: 10,
    title: "توسعه بک‌اند",
    position: "برنامه‌نویس بک‌اند",
    totalRating: 4,
    addedBy: "مریم رستمی",
    createdAt: new Date("2025-07-15"),
  },
  {
    id: 11,
    title: "طراحی گرافیک",
    position: "گرافیست",
    totalRating: 3,
    addedBy: "محمد افشار",
    createdAt: new Date("2025-07-20"),
  },
  {
    id: 12,
    title: "کیفیت نرم‌افزار",
    position: "تستر",
    totalRating: 4,
    addedBy: "عاطفه شریفی",
    createdAt: new Date("2025-07-25"),
  },
  {
    id: 13,
    title: "مدیریت فروش",
    position: "کارشناس فروش",
    totalRating: 5,
    addedBy: "احمد محمدپور",
    createdAt: new Date("2025-07-30"),
  },
  {
    id: 14,
    title: "تحلیل داده",
    position: "دیتا ساینتیست",
    totalRating: 5,
    addedBy: "زهرا کاظمی",
    createdAt: new Date("2025-08-02"),
  },
  {
    id: 15,
    title: "مدیریت شبکه",
    position: "ادمین شبکه",
    totalRating: 3,
    addedBy: "حسین تقوی",
    createdAt: new Date("2025-08-05"),
  },
  {
    id: 16,
    title: "مدیریت محصول",
    position: "مدیر محصول",
    totalRating: 4,
    addedBy: "نرگس بابایی",
    createdAt: new Date("2025-08-08"),
  },
  {
    id: 17,
    title: "پشتیبانی مشتریان",
    position: "کارشناس CRM",
    totalRating: 2,
    addedBy: "شهاب عسگری",
    createdAt: new Date("2025-08-10"),
  },
  {
    id: 18,
    title: "تحقیق و توسعه",
    position: "کارشناس R&D",
    totalRating: 5,
    addedBy: "لیلا قربانی",
    createdAt: new Date("2025-08-12"),
  },
  {
    id: 19,
    title: "مدیریت عملیات",
    position: "مدیر عملیات",
    totalRating: 4,
    addedBy: "علیرضا نصیری",
    createdAt: new Date("2025-08-14"),
  },
  {
    id: 20,
    title: "مدیریت استراتژی",
    position: "مشاور استراتژیک",
    totalRating: 5,
    addedBy: "فاطمه حیدری",
    createdAt: new Date("2025-08-15"),
  },
];
