import type { AttendanceListColumnProps } from "./columns";

export const ATTENDANCE_LIST: AttendanceListColumnProps[] = [
    {
        id: 1,
        employee: "علی رضایی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "16:00",
        tardiness: "0 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت",
    },
    {
        id: 2,
        employee: "مریم حسینی",
        date: new Date("2023-10-01"),
        status: "غایب",
        entryTime: "-",
        exitTime: "-",
        tardiness: "-",
        earlyLeave: "-",
        totalHours: "-",
    },
    {
        id: 3,
        employee: "سارا احمدی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:05",
        exitTime: "16:05",
        tardiness: "5 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت",
    },
    {
        id: 4,
        employee: "حسین محمدی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:10",
        exitTime: "16:00",
        tardiness: "10 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 50 دقیقه",
    },
    {
        id: 5,
        employee: "زهرا کریمی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "15:45",
        tardiness: "0 دقیقه",
        earlyLeave: "15 دقیقه",
        totalHours: "7 ساعت و 45 دقیقه",
    },
    {
        id: 6,
        employee: "محمد امینی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:20",
        exitTime: "16:00",
        tardiness: "20 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 40 دقیقه",
    },
    {
        id: 7,
        employee: "فاطمه موسوی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "16:10",
        tardiness: "0 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت و 10 دقیقه",
    },
    {
        id: 8,
        employee: "رضا جعفری",
        date: new Date("2023-10-01"),
        status: "غایب",
        entryTime: "-",
        exitTime: "-",
        tardiness: "-",
        earlyLeave: "-",
        totalHours: "-",
    },
    {
        id: 9,
        employee: "سمیه شریفی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:03",
        exitTime: "16:00",
        tardiness: "3 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 57 دقیقه",
    },
    {
        id: 10,
        employee: "امیر قاسمی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "15:30",
        tardiness: "0 دقیقه",
        earlyLeave: "30 دقیقه",
        totalHours: "7 ساعت و 30 دقیقه",
    },
    {
        id: 11,
        employee: "الهام مرادی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:15",
        exitTime: "16:00",
        tardiness: "15 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 45 دقیقه",
    },
    {
        id: 12,
        employee: "حسن رجبی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "16:00",
        tardiness: "0 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت",
    },
    {
        id: 13,
        employee: "ندا سلیمانی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:07",
        exitTime: "16:00",
        tardiness: "7 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 53 دقیقه",
    },
    {
        id: 14,
        employee: "مجید یوسفی",
        date: new Date("2023-10-01"),
        status: "غایب",
        entryTime: "-",
        exitTime: "-",
        tardiness: "-",
        earlyLeave: "-",
        totalHours: "-",
    },
    {
        id: 15,
        employee: "پریسا احمدی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "16:20",
        tardiness: "0 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت و 20 دقیقه",
    },
    {
        id: 16,
        employee: "سعید نادری",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:12",
        exitTime: "16:00",
        tardiness: "12 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 48 دقیقه",
    },
    {
        id: 17,
        employee: "مینا رضوانی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "15:50",
        tardiness: "0 دقیقه",
        earlyLeave: "10 دقیقه",
        totalHours: "7 ساعت و 50 دقیقه",
    },
    {
        id: 18,
        employee: "علی اکبری",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:25",
        exitTime: "16:00",
        tardiness: "25 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 35 دقیقه",
    },
    {
        id: 19,
        employee: "سحر شفیعی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "16:00",
        tardiness: "0 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت",
    },
    {
        id: 20,
        employee: "حامد صادقی",
        date: new Date("2023-10-01"),
        status: "غایب",
        entryTime: "-",
        exitTime: "-",
        tardiness: "-",
        earlyLeave: "-",
        totalHours: "-",
    },
    {
        id: 21,
        employee: "مهسا عباسی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:02",
        exitTime: "16:00",
        tardiness: "2 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 58 دقیقه",
    },
    {
        id: 22,
        employee: "یوسف مرادی",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:00",
        exitTime: "16:00",
        tardiness: "0 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "8 ساعت",
    },
    {
        id: 23,
        employee: "الهه سادات",
        date: new Date("2023-10-01"),
        status: "حاضر",
        entryTime: "08:18",
        exitTime: "16:00",
        tardiness: "18 دقیقه",
        earlyLeave: "0 دقیقه",
        totalHours: "7 ساعت و 42 دقیقه",
    }
];