import type { employeeRating } from "./column";

export const employeeData: employeeRating[] = [
  {
    id: 1,
    title: "ارزیابی عملکرد سه‌ماهه",
    employee: "علی رضایی",
    evaluationDate: new Date("2025-01-05"),
    addedBy: "مدیر منابع انسانی",
    totalRating: 5,
    createdAt: new Date("2025-01-06"),
  },
  {
    id: 2,
    title: "بازخورد ماهانه",
    employee: "سارا احمدی",
    evaluationDate: new Date("2025-01-10"),
    addedBy: "مدیر واحد فروش",
    totalRating: 4,
    createdAt: new Date("2025-01-11"),
  },
  {
    id: 3,
    title: "ارزیابی پروژه X",
    employee: "مهدی کریمی",
    evaluationDate: new Date("2025-02-01"),
    addedBy: "سرپرست تیم",
    totalRating: 3,
    createdAt: new Date("2025-02-02"),
  },
  {
    id: 4,
    title: "ارزیابی عملکرد",
    employee: "نگار محمدی",
    evaluationDate: new Date("2025-02-05"),
    addedBy: "مدیرعامل",
    totalRating: 4,
    createdAt: new Date("2025-02-06"),
  },
  {
    id: 5,
    title: "بازبینی مالی",
    employee: "رضا حسینی",
    evaluationDate: new Date("2025-02-10"),
    addedBy: "مدیر مالی",
    totalRating: 5,
    createdAt: new Date("2025-02-11"),
  },
  {
    id: 6,
    title: "بررسی پشتیبانی",
    employee: "الهام نادری",
    evaluationDate: new Date("2025-02-15"),
    addedBy: "سرپرست پشتیبانی",
    totalRating: 2,
    createdAt: new Date("2025-02-16"),
  },
  {
    id: 7,
    title: "ارزیابی کار تیمی",
    employee: "امین مرادی",
    evaluationDate: new Date("2025-03-01"),
    addedBy: "مدیر منابع انسانی",
    totalRating: 4,
    createdAt: new Date("2025-03-02"),
  },
  {
    id: 8,
    title: "کیفیت محتوا",
    employee: "سمانه موسوی",
    evaluationDate: new Date("2025-03-05"),
    addedBy: "مدیر مارکتینگ",
    totalRating: 3,
    createdAt: new Date("2025-03-06"),
  },
  {
    id: 9,
    title: "ارزیابی کمپین تبلیغاتی",
    employee: "کامران طاهری",
    evaluationDate: new Date("2025-03-12"),
    addedBy: "مدیر تبلیغات",
    totalRating: 5,
    createdAt: new Date("2025-03-13"),
  },
  {
    id: 10,
    title: "بازبینی کد",
    employee: "مریم رستمی",
    evaluationDate: new Date("2025-03-18"),
    addedBy: "رهبر تیم فنی",
    totalRating: 4,
    createdAt: new Date("2025-03-19"),
  },
  {
    id: 11,
    title: "کیفیت طراحی",
    employee: "محمد افشار",
    evaluationDate: new Date("2025-03-20"),
    addedBy: "مدیر طراحی",
    totalRating: 3,
    createdAt: new Date("2025-03-21"),
  },
  {
    id: 12,
    title: "تست نرم‌افزار",
    employee: "عاطفه شریفی",
    evaluationDate: new Date("2025-03-25"),
    addedBy: "مدیر کیفی",
    totalRating: 4,
    createdAt: new Date("2025-03-26"),
  },
  {
    id: 13,
    title: "عملکرد فروش",
    employee: "احمد محمدپور",
    evaluationDate: new Date("2025-04-01"),
    addedBy: "مدیر فروش",
    totalRating: 5,
    createdAt: new Date("2025-04-02"),
  },
  {
    id: 14,
    title: "تحلیل داده‌ها",
    employee: "زهرا کاظمی",
    evaluationDate: new Date("2025-04-05"),
    addedBy: "سرپرست دیتا",
    totalRating: 5,
    createdAt: new Date("2025-04-06"),
  },
  {
    id: 15,
    title: "ارزیابی امنیت شبکه",
    employee: "حسین تقوی",
    evaluationDate: new Date("2025-04-10"),
    addedBy: "مدیر IT",
    totalRating: 3,
    createdAt: new Date("2025-04-11"),
  },
  {
    id: 16,
    title: "بررسی مدیریت محصول",
    employee: "نرگس بابایی",
    evaluationDate: new Date("2025-04-12"),
    addedBy: "مدیر محصول",
    totalRating: 4,
    createdAt: new Date("2025-04-13"),
  },
  {
    id: 17,
    title: "ارزیابی خدمات مشتریان",
    employee: "شهاب عسگری",
    evaluationDate: new Date("2025-04-15"),
    addedBy: "مدیر CRM",
    totalRating: 2,
    createdAt: new Date("2025-04-16"),
  },
  {
    id: 18,
    title: "تحقیق و توسعه",
    employee: "لیلا قربانی",
    evaluationDate: new Date("2025-04-18"),
    addedBy: "مدیر R&D",
    totalRating: 5,
    createdAt: new Date("2025-04-19"),
  },
  {
    id: 19,
    title: "مدیریت عملیات",
    employee: "علیرضا نصیری",
    evaluationDate: new Date("2025-04-22"),
    addedBy: "مدیر عملیات",
    totalRating: 4,
    createdAt: new Date("2025-04-23"),
  },
  {
    id: 20,
    title: "استراتژی سازمان",
    employee: "فاطمه حیدری",
    evaluationDate: new Date("2025-04-25"),
    addedBy: "مدیر استراتژی",
    totalRating: 5,
    createdAt: new Date("2025-04-26"),
  },
];
